#!/bin/bash
# Criado em 28/09/2020

WORKDIR=$(pwd)
INTERPRETADOR='/usr/bin/python3'

if [ -z $1 ]; then
    echo "Informe um nome de arquivo."   
else
    arquivo="$WORKDIR/$1.py"
    if [ -f $arquivo ]; then
        echo "$arquivo já existe"
    else
        touch $arquivo
        chmod +x $arquivo
        echo -e "#!$INTERPRETADOR\n" > $arquivo
        echo "$arquivo criado!!!"
    fi
fi
